apiVersion: v1
kind: Service
metadata:
  name: rocketdex-service
spec:
  type: NodePort
  selector:
    app: rocketdex
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30303
