apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex
  labels:
    app: rocketdex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      containers:
      - name: rocketdex
        image: ghcr.io/tabatskyi/gh-actions-workshop:fb0533f
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
