name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Save Docker image
      run: |
        docker pull ghcr.io/tabatskyi/gh-actions-workshop:fb0533f || docker build -t ghcr.io/tabatskyi/gh-actions-workshop:fb0533f
        docker save -o rocketdex-image.tar ghcr.io/tabatskyi/gh-actions-workshop:fb0533f

    - name: Copy Docker image to EC2
      run: |
        echo "$EC2_SSH_KEY" > ~/key.pem
        chmod 600 ~/key.pem
        scp -o StrictHostKeyChecking=no -i ~/key.pem rocketdex-image.tar ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/

    - name: Load image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/key.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl apply -f /home/ubuntu/rocketdex-deployment.yml
          kubectl apply -f /home/ubuntu/rocketdex-service.yml
        EOF


    - name: Copy manifests to EC2
      run: scp -o StrictHostKeyChecking=no -i ~/key.pem k8s/*.yml ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/

    - name: Apply Kubernetes manifests
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/key.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          sudo kubectl apply -f /home/ubuntu/rocketdex-deployment.yml
          sudo kubectl apply -f /home/ubuntu/rocketdex-service.yml
        EOF
