name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Save Docker image
      run: |
        docker pull ghcr.io/tabatskyi/gh-actions-workshop:fb0533f || docker build -t ghcr.io/tabatskyi/gh-actions-workshop:fb0533f
        docker save -o rocketdex-image.tar ghcr.io/tabatskyi/gh-actions-workshop:fb0533f

    - name: Copy Docker image to EC2
      run: scp -i ${{ secrets.EC2_SSH_KEY }} rocketdex-image.tar ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/

    - name: Load image into Minikube
      run: ssh -i "C:\Users\Vasenka\Downloads\key2.pem" ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
           minikube ssh "docker load < /home/docker/rocketdex-image.tar"
           echo "docker image loaded"
           EOF

    - name: Copy manifests to EC2
      run: scp -i ${{ secrets.EC2_SSH_KEY }} k8s/*.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/

    - name: Apply Kubernetes manifests
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          kubectl apply -f /home/ubuntu/rocketdex-deployment.yml
          kubectl apply -f /home/ubuntu/rocketdex-service.yml
        EOF
